image: docker:24.0.5
services:
  - docker:24.0.5-dind

.standard-rules: # Make a hidden job to hold the common rules
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: ""
  PULUMI_CONFIG_PASSPHRASE: $PULUMI_ACCESS_TOKEN
  PULUMI_ACCESS_TOKEN: $PULUMI_ACCESS_TOKEN
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_REGION: "us-east-1"

update:
  stage: deploy
  image:
    name: pulumi/pulumi
    entrypoint: [""]
  before_script:
    - curl https://nitric.io/install | bash
    - export PATH=$PATH:$HOME/.nitric/bin
    - pulumi login
    - apt-get install sudo ca-certificates curl gnupg -y
    - apt-get install docker.io docker-buildx-plugin -y
  script:
    - export PATH=$PATH:$HOME/.pulumi/bin
    - export PATH=$PATH:$HOME/.nitric/bin
    - dockerd &> /dev/null &
    - docker buildx create --driver=docker-container --name=buildkit-builder --use
    - yarn install
    - nitric up --ci -v2
