image: docker:24.0.5
services:
  - docker:24.0.5-dind

.standard-rules: # Make a hidden job to hold the common rules
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - deploy

update:
  stage: deploy
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: ""
    PULUMI_CONFIG_PASSPHRASE: $PULUMI_ACCESS_TOKEN
    PULUMI_ACCESS_TOKEN: $PULUMI_ACCESS_TOKEN
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_REGION: "us-east-1"
  before_script:
    - apk update
    - apk add curl bash
    - OSTYPE=linux-musl curl https://nitric.io/install | bash
    - export PATH=$PATH:$HOME/.nitric/bin
    - curl -fsSL https://get.pulumi.com/ | bash
    - export PATH=$PATH:$HOME/.pulumi/bin
    - pulumi login
    - apk add docker.io docker-buildx-plugin nodejs
    - npm i -g yarn
  script:
    - export PATH=$PATH:$HOME/.pulumi/bin
    - export PATH=$PATH:$HOME/.nitric/bin
    - docker buildx create --driver=docker-container --name=buildkit-builder --use
    - yarn install
    - nitric up --ci -v2
