image: docker:24.0.5
services:
  - docker:24.0.5-dind

.standard-rules: # Make a hidden job to hold the common rules
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - deploy

update:
  stage: deploy
  image:
    name: pulumi/pulumi
    entrypoint: [""]
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: ""
    PULUMI_CONFIG_PASSPHRASE: $PULUMI_ACCESS_TOKEN
    PULUMI_ACCESS_TOKEN: $PULUMI_ACCESS_TOKEN
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_REGION: "us-east-1"
  before_script:
    - curl https://nitric.io/install | bash
    - export PATH=$PATH:$HOME/.nitric/bin
    - pulumi login
    - apt-get update -y
    - apt-get install sudo ca-certificates curl gnupg -y
    - install -m 0755 -d /etc/apt/keyrings
    - curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    - chmod a+r /etc/apt/keyrings/docker.gpg
    - echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian | "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    - apt-get update -y
    - apt-get install docker.io docker-buildx-plugin -y
    - mkdir -p /etc/apt/keyrings
    - curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
    - NODE_MAJOR=20
    - echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
    - apt-get update -y
    - apt-get install -y nodejs
    - npm i -g yarn
  script:
    - export PATH=$PATH:$HOME/.pulumi/bin
    - export PATH=$PATH:$HOME/.nitric/bin
    - docker buildx create --driver=docker-container --name=buildkit-builder --use
    - yarn install
    - nitric up --ci -v2
