name: Nitric
on:
  push:
    branches:
      - main
jobs:
  up:
    name: Update AWS
    runs-on: ubuntu-latest
    environment: github-action-test
    steps:
      - uses: actions/checkout@v4
      - uses: nitrictech/actions@v1
        with:
          command: up
          stack-name: aws
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  audit:
    name: Run cloudsplaining
    runs-on: ubuntu-latest
    environment: github-action-test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - pip3 install --user cloudsplaining
      - cloudsplaining download
      - cloudsplaining scan --input-file default.json --skip-open-report
        uses: actions/upload-artifact@v3
        with:
          name: cloudsplaining-report
          path: iam-report-default.html
          retention-days: 7
  down:
    name: Destroy AWS
    needs: up
    runs-on: ubuntu-latest
    environment: github-action-test
    steps:
      - uses: actions/checkout@v4
      - uses: nitrictech/actions@v1
        with:
          command: down
          stack-name: aws
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
