name: Nitric
on:
  push:
    branches:
      - main
jobs:
  up:
    name: Update AWS
    runs-on: ubuntu-latest
    environment: github-action-test
    steps:
      - uses: actions/checkout@v4
      - uses: nitrictech/actions@v1
        with:
          command: up
          stack-name: aws
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  audit:
    name: Run cloudsplaining
    needs: up
    runs-on: ubuntu-latest
    environment: github-action-test
    steps:
      - uses: actions/setup-python@v4
      - run: pip3 install --user cloudsplaining
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: cloudsplaining download
      - run: cloudsplaining scan --input-file default.json --skip-open-report
      - uses: actions/upload-artifact@v3
        with:
          name: cloudsplaining-report
          path: iam-report-default.html
          retention-days: 7
  down:
    name: Destroy AWS
    needs: audit
    runs-on: ubuntu-latest
    environment: github-action-test
    steps:
      - uses: actions/checkout@v4
      - uses: nitrictech/actions@v1
        with:
          command: down
          stack-name: aws
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
